#include <iostream>
#include <cstdio>
#include <cstring>
#include <algorithm>
#include <climits>
#include <vector>
#include <map>
#include <fstream>
#include <memory>
#include <queue>

using std::string;
using std::vector;
using std::queue;
using std::map;
using std::cout;
using std::endl;
using std::shared_ptr;
using std::make_shared;
using std::dynamic_pointer_cast;
